services:
  wordpress:
    build: .
    ports:
      - "8080:80"
      - "7080:7080"
    volumes:
      - wp_app:/var/www/html
    init: true
    env_file: ".env"
    restart: unless-stopped

  mail-relay:
    build: ./mail-relay
    env_file: ".env"
    restart: unless-stopped

  mariadb:
    build: ./mariadb
    env_file: ".env"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress_password}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE:-1}

  valkey:
    image: valkey/valkey:latest
    command: valkey-server --protected-mode no --maxmemory ${VALKEY_MAX_MEMORY:-64mb} --maxmemory-policy allkeys-lru --save ""
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    profiles:
      - tools
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    profiles:
      - tools
    ports:
      - "8082:80"
    volumes:
      - wp_app:/srv
      - filebrowser_data:/database
      - filebrowser_settings:/config
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    profiles:
      - debug
    ports:
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    profiles:
      - mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    restart: unless-stopped

volumes:
  wp_app:
  db_data:
  filebrowser_data:
  filebrowser_settings:
