services:
  wordpress:
    build: .
    entrypoint: [ "bash", "/usr/local/bin/docker-entrypoint-extra.sh" ]
    volumes:
      - wp_app:/var/www/html
      - ./php:/tmp/php:ro
      - ./php/docker-entrypoint-extra.sh:/usr/local/bin/docker-entrypoint-extra.sh:ro
      - ./ols:/tmp/ols:ro
      - ../files/cubaan.md:/tmp/cubaan.md
    init: true
    env_file: ".env"
    restart: unless-stopped

  mail-relay:
    build: ./mail-relay
    env_file: ".env"
    restart: unless-stopped

  valkey:
    image: valkey/valkey:latest
    command: valkey-server --protected-mode no
    restart: unless-stopped

volumes:
  wp_app:
