docRoot                   /var/www/html
index  {
  useServer               0
  indexFiles              index.php, index.html
}


extprocessor filemanager {
  type                    proxy
  address                 http://file-manager:80
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context FILE_MANAGER_PATH_PLACEHOLDER {
  type                    proxy
  handler                 filemanager
  addDefaultCharset       off
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  rules                   <<<END_rules
# 1. Database Manager (Secret Path)
RewriteRule ^/?DB_MANAGER_PATH_PLACEHOLDER/?$ /adminer-auth.php [L]

# 2. File Manager (Redirect for trailing slash)
RewriteRule ^/?FILE_MANAGER_PATH_STRIPPED$ FILE_MANAGER_PATH_STRIPPED/ [R=301,L]

# 3. Block direct access to the real filename
RewriteCond %{THE_REQUEST} /adminer-auth\.php [NC]
RewriteRule .* - [F,L]

# 4. WordPress Basic Rewrites
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
  END_rules
}
