docRoot                   $VH_ROOT
index  {
  useServer               0
  indexFiles              index.php, index.html
}

scripthandler  {
  add                     fcgi:wordpress php
}

extprocessor wordpress {
  type                    fcgi
  address                 wordpress:9000
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

extprocessor filemanager {
  type                    proxy
  address                 http://file-manager:80
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context FILE_MANAGER_PATH_PLACEHOLDER {
  type                    proxy
  handler                 filemanager
  addDefaultCharset       off
}

context DB_MANAGER_PATH_PLACEHOLDER {
  type                    static
  location                $VH_ROOT/adminer-auth.php
  addDefaultCharset       off
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  rules                   <<<END_rules
RewriteRule ^FILE_MANAGER_PATH_STRIPPED$ FILE_MANAGER_PATH_STRIPPED/ [R=301,L]

# WordPress Basic Rewrites
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
  END_rules
}
