docRoot                   $VH_ROOT
index  {
  useServer               0
  indexFiles              index.php, index.html
}

scripthandler  {
  add                     fcgi-auth:wordpress php
}

extprocessor wordpress {
  type                    fcgi
  address                 wordpress:9000
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

extprocessor filemanager {
  type                    proxy
  address                 http://file-manager:80
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context /file-manager/ {
  type                    proxy
  handler                 filemanager
  addDefaultCharset       off
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
}
