[www]
pm = FPM_PM_TYPE_PLACEHOLDER
pm.max_children = FPM_MAX_CHILDREN_PLACEHOLDER
pm.start_servers = FPM_START_SERVERS_PLACEHOLDER
pm.min_spare_servers = FPM_MIN_SPARE_SERVERS_PLACEHOLDER
pm.max_spare_servers = FPM_MAX_SPARE_SERVERS_PLACEHOLDER
pm.process_idle_timeout = FPM_IDLE_TIMEOUT_PLACEHOLDER
pm.max_requests = 1000

; Make sure environment variables are passed to PHP
clear_env = no
